language: php
php:
  - 7.4.3

cache:
  directories:
    - node_modules
    - vendor

notifications:
  email:
    recipients:
      - taehyungkim@outlook.com

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: TaehyungAlexKim/Application-Project-Rental-Buddy
    branch: main
  bucket: rentalbuddy
  region: us-east-2
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: rentalbuddy
  key: latest.zip
  bundle_type: zip
  application: rentalbuddy-codedeploy
  deployment_group: rentalGrp
  region: us-east-2
  on: *2


script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip    